version: '2'
services:
  gpt2-service:
    build:
      context: gpt2-service/
      dockerfile: Dockerfile
      args:
        - OPENJDK_TAG=8u232
        - SBT_VERSION=1.3.13 
    container_name: gpt2_service
    restart: always

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: newsgen_frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - "gpt2-service"
    restart: always
