version: '2'
services:
  gpt2-service:
    build:
      context: gpt2-service/
      dockerfile: Dockerfile
      args:
        - OPENJDK_TAG=8u232
        - SBT_VERSION=1.3.13
    container_name: gpt2_service
    restart: always
    environment:
      - SERVICE_IP=${SERVICE_IP}
      - SERVICE_PORT=${SERVICE_PORT}
      - SERVICE_SECRET=${SERVICE_SECRET}
