version: '2'
services:
  gpt2-service:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - OPENJDK_TAG=8u232
        - SBT_VERSION=1.3.13
    container_name: gpt2_service
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}
    restart: always
    ports:
      - 9000:9000

