version: '2'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    restart: always
    environment:
      - GPT2_SERVICE_DOMAIN=${GPT2_SERVICE_DOMAIN}